---
sudo: false
dist: trusty
language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade flake8

script:
  - flake8 kinesyslog/ utils/

notifications:
  email: false
